name: Docker Image CI

on:
  push:
    branches: [ "master" , "x264_profile"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/Dockerfile.prod
          load: true
          tags: webmultimedia/http-streaming-server:master
      -
        name: Test
        run: |
          cp -r tests/* Videos/ 
          docker-compose -f docker-compose-prod.yml run --rm web ./wait-for-it.sh db:5432 -- python3 manage.py test
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/Dockerfile.prod
          push: true
          tags: webmultimedia/http-streaming-server:master
